# Generated by Django 5.1.1 on 2024-09-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['upvotes', 'created_on']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['upvotes', 'created_on']},
        ),
    ]
