# Generated by Django 4.2.16 on 2024-10-07 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0007_comment_upvoters'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoted_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
